name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-token-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Check for GitHub access token
      run: |
        if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
          echo "GITHUB_TOKEN is not set"
          exit 1
        else
          echo "GITHUB_TOKEN is set"
        fi